### ISSUE TITLE
Integrate this awesome api with angularJS app.

### ISSUE THREAD

**Issue by mikeandersun** [bahmutov/iframe-api#21]
I would like to use this api with an anugalrjs app that control the iframe. Is there any restricts?
Can you give me some starting point?
thanks

**Comment by bahmutov** [comment]
Hi Mike,
Take a look at my blog post [Testing AngularJS application at the model level using iframe API](http://bahmutov.calepin.co/testing-angularjs-application-at-the-model-level-using-iframe-api.html). The example repo is at [bahmutov/todomvc-angularjs-iframe-test](https://github.com/bahmutov/todomvc-angularjs-iframe-test) and the live demo at [this page](http://glebbahmutov.com/todomvc-angularjs-iframe-test/)
