### ISSUE TITLE
Demo not working in Fireox

### ISSUE THREAD

**Issue by ianflitman** [bahmutov/iframe-api#22]
Hi This looks really good. Just thought I would point out that your demo site showing the handshakes etc works in Chrome but not Firefox. Is that a limitation of library or just an HTML gotcha in the Firefox html? This is currently making me think twice about using it....

all best
and keep up the good work,
ian

**Comment by bahmutov** [comment]
Hmm, never tried it on Firefox, will take a look. Don't see why it would not work, unless there is some permission that needs to be set on the `iframe` tag itself.

**Comment by bahmutov** [comment]
I opened dev tools in the Firefox, the handshake is happening, it is a problem mirroring console.log calls into the DIV, see the attached screenshot. 
![screen shot 2015-03-11 at 9 32 31 am](https://cloud.githubusercontent.com/assets/2212006/6597263/abc08ca0-c7d1-11e4-93c5-bbef670b167f.png)

**Comment by bahmutov** [comment]
Ok, I updated console log dependency to latest, seems to show the messages in Firefox now.

**Comment by ianflitman** [comment]
Hi Gleb,

Thanks so much for looking into that for me. We aim to use it across browsers so I might also test it out on Internet Exploder as well as Safari. I must say I really like the look of the library itself and I showed it to my future collaborators here at EPFL and they seemed to like the idea of it too. Such a neat idea mutually injecting apis between iframes on handshake. We might need to communicate with more than one iframe so I have a little niggling doubt about APIs potentially namespace clashing but that is probably unfounded...I need to get down and code with the library. Hopefully, in the next couple of weeks. I will keep you posted as to how it is going if you like. Again, a big bunch of thanks, Ian

**Comment by bahmutov** [comment]
Absolutely, glad to hear that this is useful. Let me know if there are
features that would make your life easier. Plus fork / pull requests are
always welcome!

Gleb
